version: 2.1

jobs:
  build:
    docker:
      - image: cypress/browsers:node12.13.0-chrome80-ff74
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: dependencies-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache

workflows:
  Build and Test:
    jobs:
      - build
