name: Setup integration test
description: Prepares the environment to run an integration test

inputs:
  integration:
    description: The integration test to run
    required: true
  node:
    description: The Node version to use
    required: false
    default: 18
  dotenv:
    description: The path to the .env file
    required: false
    default: .env.sample

runs:
  using: composite

  steps:
    - uses: pnpm/action-setup@v2

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node }}
        cache: 'pnpm'

    - name: Update /etc/hosts
      shell: bash
      run: |
        sudo echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts

    - name: Move dotenv file
      shell: bash
      run: |
        mv examples/${{ inputs.integration }}/${{ inputs.dotenv }} examples/${{ inputs.integration }}/.env

    - name: Install dependencies
      shell: bash
      run: |
        pnpm ci
        pnpm ci --prefix=examples/users-api
        pnpm i --prefix=examples/${{ inputs.integration }} --no-package-lock --legacy-peer-deps

    - name: Start mock API server
      shell: bash
      run: pnpm run start --prefix=examples/users-api &

    - name: Start application
      shell: bash
      run: pnpm run start --prefix=examples/${{ inputs.integration }} &
