name: Integration Tests

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  NODE_VERSION: 18
  DOMAIN: your-tenant.auth0.com
  AUDIENCE: https://api.example.com/users
  PORT: 3001
  NEXT_PUBLIC_DOMAIN: your-tenant.auth0.com
  NEXT_PUBLIC_CLIENT_ID: yourclientid
  NEXT_PUBLIC_AUDIENCE: https://api.example.com/users
  NEXT_PUBLIC_API_PORT: 3001
  GATSBY_DOMAIN: your-tenant.auth0.com
  GATSBY_CLIENT_ID: yourclientid
  GATSBY_AUDIENCE: https://api.example.com/users
  GATSBY_API_PORT: 3001
  SKIP_PREFLIGHT_CHECK: true
  REACT_APP_DOMAIN: your-tenant.auth0.com
  REACT_APP_CLIENT_ID: yourclientid
  REACT_APP_AUDIENCE: https://api.example.com/users
  REACT_APP_API_PORT: 3001

jobs:
  integration:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build package
        uses: ./.github/actions/build
        with:
          node: ${{ env.NODE_VERSION }}

      - name: Install test dependencies
        run: npm run install:examples

      - name: Run tests
        run: npm run test

      - name: Run integration tests
        run: npm run test:integration
