name: Integration Tests

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

env:
  NODE_VERSION: 18
  DOMAIN: your-tenant.auth0.com
  AUDIENCE: https://api.example.com/users
  PORT: 3001

jobs:
  test-cra:
    name: Run cra-react-router tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare integration test
        uses: ./.github/actions/integration
        with:
          integration: 'cra-react-router'
          node: ${{ env.NODE_VERSION }}

      - name: Run integration tests
        run: |
          npm run test:cra
        env:
          SKIP_PREFLIGHT_CHECK: true
          REACT_APP_DOMAIN: your-tenant.auth0.com
          REACT_APP_CLIENT_ID: yourclientid
          REACT_APP_AUDIENCE: https://api.example.com/users
          REACT_APP_API_PORT: 3001

  test-gatsby:
    name: Run Gatsby tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare integration test
        uses: ./.github/actions/integration
        with:
          integration: 'gatsby-app'
          node: ${{ env.NODE_VERSION }}

      - name: Run integration tests
        run: |
          npm run test:gatsby
        env:
          GATSBY_DOMAIN: your-tenant.auth0.com
          GATSBY_CLIENT_ID: yourclientid
          GATSBY_AUDIENCE: https://api.example.com/users
          GATSBY_API_PORT: 3001

  test-nextjs:
    name: Run NextJS tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare integration test
        uses: ./.github/actions/integration
        with:
          integration: 'nextjs-app'
          node: ${{ env.NODE_VERSION }}

      - name: Run integration tests
        run: |
          npm run test:nextjs
        env:
          NEXT_PUBLIC_DOMAIN: your-tenant.auth0.com
          NEXT_PUBLIC_CLIENT_ID: yourclientid
          NEXT_PUBLIC_AUDIENCE: https://api.example.com/users
          NEXT_PUBLIC_API_PORT: 3001
